// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

// =============================================================================
// RELEASE_BASE_URL: Update this when creating a new release.
// Run scripts/build-release.sh in pear-wrk-wdk-jsonrpc to generate the
// binary-targets.swift snippet with correct URLs and checksums.
// =============================================================================
let releaseBaseURL = "RELEASE_URL_HERE"
// e.g. "https://github.com/ArcadeLabsInc/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0"

let package = Package(
    name: "WdkSwiftCore",
    platforms: [
        .iOS(.v14),
        .macOS(.v11)
    ],
    products: [
        .library(
            name: "WdkSwiftCore",
            targets: ["WdkSwiftCore"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/holepunchto/bare-kit-swift", branch: "main")
    ],
    targets: [
        // ---------------------------------------------------------------------
        // Main target
        // ---------------------------------------------------------------------
        .target(
            name: "WdkSwiftCore",
            dependencies: [
                .product(name: "BareKit", package: "bare-kit-swift"),
                "bare_buffer",
                "bare_crypto",
                "bare_dns",
                "bare_fs",
                "bare_hrtime",
                "bare_inspect",
                "bare_os",
                "bare_performance",
                "bare_pipe",
                "bare_signals",
                "bare_tcp",
                "bare_tls",
                "bare_tty",
                "bare_type",
                "bare_url",
                "bare_zlib",
                "sodium_native",
            ]
        ),

        // ---------------------------------------------------------------------
        // Native addon xcframeworks (auto-downloaded by SPM)
        //
        // These are generated by bare-link and distributed via GitHub releases.
        // To update: run scripts/build-release.sh in pear-wrk-wdk-jsonrpc,
        // then paste the generated binary-targets.swift snippet below.
        // ---------------------------------------------------------------------
        .binaryTarget(
            name: "bare_buffer",
            url: "\(releaseBaseURL)/bare-buffer.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_crypto",
            url: "\(releaseBaseURL)/bare-crypto.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_dns",
            url: "\(releaseBaseURL)/bare-dns.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_fs",
            url: "\(releaseBaseURL)/bare-fs.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_hrtime",
            url: "\(releaseBaseURL)/bare-hrtime.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_inspect",
            url: "\(releaseBaseURL)/bare-inspect.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_os",
            url: "\(releaseBaseURL)/bare-os.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_performance",
            url: "\(releaseBaseURL)/bare-performance.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_pipe",
            url: "\(releaseBaseURL)/bare-pipe.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_signals",
            url: "\(releaseBaseURL)/bare-signals.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_tcp",
            url: "\(releaseBaseURL)/bare-tcp.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_tls",
            url: "\(releaseBaseURL)/bare-tls.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_tty",
            url: "\(releaseBaseURL)/bare-tty.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_type",
            url: "\(releaseBaseURL)/bare-type.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_url",
            url: "\(releaseBaseURL)/bare-url.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "bare_zlib",
            url: "\(releaseBaseURL)/bare-zlib.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
        .binaryTarget(
            name: "sodium_native",
            url: "\(releaseBaseURL)/sodium-native.xcframework.zip",
            checksum: "CHECKSUM_HERE"
        ),
    ]
)
