// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription


let package = Package(
    name: "WdkSwiftCore",
    platforms: [
        .iOS(.v14),
        .macOS(.v11)
    ],
    products: [
        .library(
            name: "WdkSwiftCore",
            targets: ["WdkSwiftCore"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/holepunchto/bare-kit-swift", branch: "main")
    ],
    targets: [
        // ---------------------------------------------------------------------
        // Main target
        // ---------------------------------------------------------------------
        .target(
            name: "WdkSwiftCore",
            dependencies: [
                .product(name: "BareKit", package: "bare-kit-swift"),
                "bare_buffer",
                "bare_crypto",
                "bare_dns",
                "bare_fs",
                "bare_hrtime",
                "bare_inspect",
                "bare_os",
                "bare_performance",
                "bare_pipe",
                "bare_signals",
                "bare_tcp",
                "bare_tls",
                "bare_tty",
                "bare_type",
                "bare_url",
                "bare_zlib",
                "sodium_native",
            ]
        ),

        // ---------------------------------------------------------------------
        // Native addon xcframeworks (auto-downloaded by SPM)
        //
        // These are generated by bare-link and distributed via GitHub releases.
        // To update: run scripts/build-release.sh in pear-wrk-wdk-jsonrpc,
        // then paste the generated binary-targets.swift snippet below.
        // ---------------------------------------------------------------------
        .binaryTarget(
            name: "bare_buffer",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-buffer.xcframework.zip",
            checksum: "75431afc1cc8deb8eeda4eab3795c367834d4d36b9bd04bdf7811cde646a9c1b"
        ),
        .binaryTarget(
            name: "bare_crypto",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-crypto.xcframework.zip",
            checksum: "6e81b1c81d268284eb333a0a148f0cbd1ec9f3124d671e1d8ff3cb64c34746fa"
        ),
        .binaryTarget(
            name: "bare_dns",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-dns.xcframework.zip",
            checksum: "1c7cdac9e5981187d0fa05360045aa647ea065405f7a150352165b367c085d31"
        ),
        .binaryTarget(
            name: "bare_fs",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-fs.xcframework.zip",
            checksum: "2ea454d1eff759bc87940b9bd487e39d41c5dcd7ecca68504d7787454898132b"
        ),
        .binaryTarget(
            name: "bare_hrtime",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-hrtime.xcframework.zip",
            checksum: "17d6a44a935143a28f5fea9427e7f8d46fd763785cf37c55d1d65a2101f1a90f"
        ),
        .binaryTarget(
            name: "bare_inspect",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-inspect.xcframework.zip",
            checksum: "5718b17cd093483660c573b62030a68570fe65e0f8f67c08255a6fa28ce7dbe0"
        ),
        .binaryTarget(
            name: "bare_os",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-os.xcframework.zip",
            checksum: "4cc422262893e871b877c84284663bce3a1840dbc8578a16eb6d000329ae0ccf"
        ),
        .binaryTarget(
            name: "bare_performance",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-performance.xcframework.zip",
            checksum: "26b6839f18d75b8923bbe7ca1d9fd99000bd254a2713f63b2d602ac9925ffea0"
        ),
        .binaryTarget(
            name: "bare_pipe",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-pipe.xcframework.zip",
            checksum: "8c0f09af1815584a3dcf2529ae24d282e66d83df46b66cd416b8fd30b213ad2a"
        ),
        .binaryTarget(
            name: "bare_signals",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-signals.xcframework.zip",
            checksum: "c8bee2b92c63753afe76498304db31af601aab50de7d7c180e1aab0a40dfdbd3"
        ),
        .binaryTarget(
            name: "bare_tcp",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-tcp.xcframework.zip",
            checksum: "aaa43ecfb977f0aea3df995ddb5f98d66c1ea479d1c424149e73c877ad851bd1"
        ),
        .binaryTarget(
            name: "bare_tls",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-tls.xcframework.zip",
            checksum: "bdad021ad15cc97aceef9c0146bb6a06ba8d9b2815815ab796692bf72e784b5a"
        ),
        .binaryTarget(
            name: "bare_tty",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-tty.xcframework.zip",
            checksum: "94efac527d4b5b2aaaedcf271bc0876e18b99d37e2767bc872c068c7a6e6d383"
        ),
        .binaryTarget(
            name: "bare_type",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-type.xcframework.zip",
            checksum: "242aa1475b40bba2f5e60d9a9a5c4224ae8c2103a5ffb42c6ac6d35e91c42b6f"
        ),
        .binaryTarget(
            name: "bare_url",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-url.xcframework.zip",
            checksum: "93f12cbc554c8f03c2f7bc38a0c928869e8b6cca34f451fb420b9d33ac741f4d"
        ),
        .binaryTarget(
            name: "bare_zlib",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/bare-zlib.xcframework.zip",
            checksum: "286385f3252d2692d92a2d2915cd9a730eda9f3c9d889aa73224dda86031039a"
        ),
        .binaryTarget(
            name: "sodium_native",
            url: "https://github.com/claudiovb/pear-wrk-wdk-jsonrpc/releases/download/v1.0.0-beta.1/sodium-native.xcframework.zip",
            checksum: "9f70d6e13dba8e856b5e00ee83da18eff91de3369ee1fdf3c7a8c976e375bc99"
        ),
    ]
)
